M48
; DRILL file {KiCad 7.0.9} date Sun Dec  3 00:18:10 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-03T00:18:10-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0295
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0827
%
G90
G05
T1
X5.7793Y-2.2014
X5.8876Y-2.2014
T2
X5.1Y-1.6
X5.1Y-1.9
X5.1Y-2.4
X5.1Y-2.7
X5.1Y-3.2
X5.1Y-3.5
T0
M30
